# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [3]:
s1 = pd.Series(np.random.randint(1,5,size=100,dtype='l'))
s2 = pd.Series(np.random.randint(1,4,size=100,dtype='l'))
s3 = pd.Series(np.random.randint(10000,30001,size=100,dtype='l'))
print(s1)
print(s2)
print(s3)

0     1
1     4
2     1
3     2
4     4
     ..
95    2
96    2
97    4
98    2
99    3
Length: 100, dtype: int32
0     2
1     2
2     1
3     3
4     1
     ..
95    1
96    2
97    2
98    3
99    2
Length: 100, dtype: int32
0     12530
1     21872
2     19621
3     29364
4     14923
      ...
95    17110
96    18383
97    26608
98    14665
99    12937
Length: 100, dtype: int32

### Step 3. Let's create a DataFrame by joinning the Series by column

In [5]:
house = pd.concat([s1,s2,s3],axis=1)
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       100 non-null    int32
 1   1       100 non-null    int32
 2   2       100 non-null    int32
dtypes: int32(3)
memory usage: 1.3 KB

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [6]:
house.rename(columns={0:'bedrs',1:'bathrs',2:'price_sqr_meter'},inplace=True)
house

    bedrs  bathrs  price_sqr_meter
0       1       2            12530
1       4       2            21872
2       1       1            19621
3       2       3            29364
4       4       1            14923
..    ...     ...              ...
95      2       1            17110
96      2       2            18383
97      4       2            26608
98      2       3            14665
99      3       2            12937

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [10]:
bigcolumn = pd.concat([s1, s2, s3], axis=0)
bigcolumn = bigcolumn.to_frame()
print(type(bigcolumn))
bigcolumn

<class 'pandas.core.frame.DataFrame'>

        0
0       1
1       4
2       1
3       2
4       4
..    ...
95  17110
96  18383
97  26608
98  14665
99  12937

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [11]:
len(bigcolumn)

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [12]:
bigcolumn.reset_index(drop=True,inplace=True)
bigcolumn

         0
0        1
1        4
2        1
3        2
4        4
..     ...
295  17110
296  18383
297  26608
298  14665
299  12937

[300 rows x 1 columns]